2013/10/26 19:38:35 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.username" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/helpers/CHtml.php(2529): CComponent->__get('username')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/helpers/CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'username')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/helpers/CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/views/site/login.php(29): CActiveForm->textField(Object(LoginForm), 'username')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(869): CBaseController->renderFile('/Applications/X...', Array, true)
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('login', Array, true)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php(98): CController->render('login', Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#15 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php
---
2013/10/26 19:50:30 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.email" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/models/LoginForm.php(51): CComponent->__get('email')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php(94): CModel->validate()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/26 19:52:01 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.Email" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/models/LoginForm.php(51): CComponent->__get('Email')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php(94): CModel->validate()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/26 19:53:31 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.email" is not defined.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CComponent.php:130
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/models/LoginForm.php(51): CComponent->__get('email')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php(94): CModel->validate()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('login')
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/27 21:25:27 [error] [php] include(Employee.php): failed to open stream: No such file or directory (/Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:427)
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/components/UserIdentity.php(13): spl_autoload_call()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php(94): LoginForm->validate()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): SiteController->runAction()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): SiteController->run()
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CWebApplication->run()
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/login
in /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/components/UserIdentity.php (13)
in /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/models/LoginForm.php (52)
in /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/protected/controllers/SiteController.php (94)
2013/10/27 21:27:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('page_after_logi...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page_after_logi...')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/page_after_login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/27 21:30:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('page_after_logi...')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('page_after_logi...')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/page_after_login
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/27 21:31:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Home".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('Home')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('Home')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/Home')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/Home
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/27 21:31:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Home".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('Home')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('Home')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/Home')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/Home
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
2013/10/27 21:31:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "homeUrl".' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:483
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(270): CController->missingAction('homeUrl')
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('homeUrl')
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/homeUrl')
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/appl/ProjectStage/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/appl/ProjectStage/index.php?r=site/homeUrl
HTTP_REFERER=http://localhost/yii/appl/ProjectStage/index.php?r=site/login
---
